#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRD_FILE="$ROOT_DIR/prd.json"
PROMPT_FILE="$ROOT_DIR/ralph.md"
PROGRESS_FILE="$ROOT_DIR/progress.txt"

require_file() {
  local f="$1"
  if [[ ! -f "$f" ]]; then
    echo "Missing required file: $f" >&2
    exit 1
  fi
}

require_cmd() {
  local c="$1"
  if ! command -v "$c" >/dev/null 2>&1; then
    echo "Required command not found: $c" >&2
    exit 1
  fi
}

read_json() {
  local expr="$1"
  (
    cd "$ROOT_DIR"
    node -e "const fs=require('fs');const d=JSON.parse(fs.readFileSync('prd.json','utf8'));const r=($expr);if(r===undefined||r===null){process.exit(2)};if(typeof r==='object'){console.log(JSON.stringify(r));}else{console.log(String(r));}"
  )
}

require_file "$PRD_FILE"
require_file "$PROMPT_FILE"
require_cmd git
require_cmd node
require_cmd codex

if [[ ! -f "$PROGRESS_FILE" ]]; then
  cat > "$PROGRESS_FILE" <<'EOF'
## Codebase Patterns
- Keep this section updated with reusable patterns discovered during implementation.

EOF
fi

if ! grep -q "^## Codebase Patterns" "$PROGRESS_FILE"; then
  tmp_file="$(mktemp)"
  {
    echo "## Codebase Patterns"
    echo "- Keep this section updated with reusable patterns discovered during implementation."
    echo
    cat "$PROGRESS_FILE"
  } > "$tmp_file"
  mv "$tmp_file" "$PROGRESS_FILE"
fi

branch_name="$(read_json "d.branchName")"
if [[ -z "$branch_name" ]]; then
  echo "branchName is missing in prd.json" >&2
  exit 1
fi

next_task_json="$(read_json "(() => { const tasks=(d.tasks||[]).filter(t=>t&&t.passes===false).sort((a,b)=>(a.priority??1e9)-(b.priority??1e9)); return tasks[0]||null; })()")" || true

if [[ -z "${next_task_json:-}" || "$next_task_json" == "null" ]]; then
  echo "<promise>COMPLETE</promise>"
  exit 0
fi

task_id="$(node -e "const t=$next_task_json;console.log(t.id||'UNKNOWN');")"
task_title="$(node -e "const t=$next_task_json;console.log(t.title||'Untitled');")"

current_branch="$(git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD)"
if [[ "$current_branch" != "$branch_name" ]]; then
  if git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$branch_name"; then
    git -C "$ROOT_DIR" checkout "$branch_name"
  else
    git -C "$ROOT_DIR" checkout -b "$branch_name" main
  fi
fi

tmp_prompt="$(mktemp)"
cat "$PROMPT_FILE" > "$tmp_prompt"
cat >> "$tmp_prompt" <<EOF

---

## Session Constraint (Generated by ralph_once.sh)

Implement exactly one story this run:
- Story ID: $task_id
- Story Title: $task_title
- Story JSON: $next_task_json

Rules for this run:
- Work only on this story.
- Follow all instructions in ralph.md.
- Update prd.json: set only this story's \`passes\` to true when done.
- Append an entry to progress.txt using the required format.
- If all tasks become complete, output: <promise>COMPLETE</promise>
EOF

echo "Running Codex for $task_id - $task_title"
set +e
codex exec --full-auto -C "$ROOT_DIR" "$(cat "$tmp_prompt")"
codex_exit=$?
set -e
rm -f "$tmp_prompt"

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
changed_files="$(git -C "$ROOT_DIR" status --short | awk '{print $2}')"
last_commit="$(git -C "$ROOT_DIR" log -1 --pretty=format:'%h %s' 2>/dev/null || true)"
if [[ -z "$last_commit" ]]; then
  last_commit="none"
fi

{
  echo "## [$timestamp] - $task_id (runner)"
  echo "Thread: $thread_url"
  echo "- Runner executed Codex session for $task_id - $task_title"
  echo "- Exit code: $codex_exit"
  echo "- Files changed in working tree after run:"
  if [[ -n "$changed_files" ]]; then
    while IFS= read -r f; do
      [[ -n "$f" ]] && echo "  - $f"
    done <<< "$changed_files"
  else
    echo "  - none"
  fi
  echo "- Latest commit: $last_commit"
  echo "---"
} >> "$PROGRESS_FILE"

if [[ $codex_exit -ne 0 ]]; then
  echo "Codex session exited with code $codex_exit" >&2
  exit "$codex_exit"
fi

echo "Pushing branch $branch_name to origin"
git -C "$ROOT_DIR" push -u origin "$branch_name"

echo "Completed session for $task_id"
